matrix:
  include:
  - env: CONTAINERD_BRANCH=master
  - env: CONTAINERD_BRANCH=release/1.3
    go: 
    - 1.12.15
dist: bionic
sudo: required
language: go
os:
- linux
go:
- "1.13.6"
branches:
  only:
  - master
addons:
  apt:
    packages:
    - btrfs-tools
    - libseccomp-dev
before_install:
- uname -r
install:
- mkdir -p "${GOPATH}/src/github.com/containerd/containerd"
- git clone --branch "${CONTAINERD_BRANCH}" https://github.com/containerd/containerd.git "${GOPATH}/src/github.com/containerd/containerd"
- export RUNC_COMMIT=$(grep opencontainers/runc ${GOPATH}/src/github.com/containerd/containerd/vendor.conf | cut -d " " -f 2)
- export RUNC_COMMIT="dc9208a3303feef5b3839f4323d9beb36df0a9dd" # v1.0.0-rc10, TODO: remove this hack
- go get -d github.com/opencontainers/runc
- cd $GOPATH/src/github.com/opencontainers/runc
- git checkout $RUNC_COMMIT
- cd $GOPATH/src/github.com/containerd/containerd
script:
- export gitVersion="$(cd "${GOPATH}/src/github.com/containerd/containerd" && git describe --match 'v[0-9]*' --dirty='.m' --always)+kind-ci"
- export TRAVIS_TAG="containerd-${gitVersion#v}"
- echo "${TRAVIS_TAG}"
- cd $TRAVIS_BUILD_DIR
- if curl -sSLf "https://api.github.com/repos/kind-ci/containerd-nightlies/releases/tags/${TRAVIS_TAG}" -o /dev/null; then echo "Release exists, skip the build" ; unset TRAVIS_TAG ; exit 0 ; fi
- sudo PATH=$PATH GOPATH=$GOPATH $TRAVIS_BUILD_DIR/release-containerd-nightly.sh
before_deploy:
- git config --local user.name "kind-ci-robot"
- git config --local user.email "46937763+kind-ci-robot@users.noreply.github.com"
- cd $TRAVIS_BUILD_DIR
- if git rev-parse "${TRAVIS_TAG}"; then echo "Deleting old tag" && git tag -d "${TRAVIS_TAG}"; fi
- git tag "${TRAVIS_TAG}"
deploy:
  provider: releases
  api_key:
    secure: "2/HTS9iOAh6vYJoqVKXlIgR24eeasSsnl8hg2NuPq0aDH9DndpdIBOv0a+n4KZ/XZXIiwXxoYr8v3u8EKbSLG4QS6Zh58Ypi3mWY3dfGCOcxQH007eKVcVSR0CAVdf1JEAYBlQglWLoXMfle+6UgS5kItTEmwbYjvK0V92plKu+QJbV5zzf/sfOz4Fk/GsZ61mJhBG6F2GcG6/uzmJVCPFF+cPkWO0+8e793Y6AjcYnxqBPa8n0gZvhXNzXr8la1D1HPAV9xZEWyUlELeTA3s685eSqOP6S4bkEw+6f+NGTlXBjzlq8Yajt7M87WmnDq3uqJ4aQUMUr5mVFfVQR1owVfEjMssiz3ZSvrG051YLSdno9FGT4Ix56co5gjvCom7GaZELSa5qFGZxwBoa8qOhYz6XRbJerSV2XFz0JZnXIm8YujY3YKsSd1RERcwWINFmOVLOlYKPZJLIjSul2K8gLLwoTu8rysLb1I3JSp5gtolBaf4wVPyXVplFco1/uluGKH8PObb3uRM6ORB8yKKq+BiETxYJmr4JyPPNYxAEOqK23OmWcLu0qwTpmQf8ZD4imm7FcdIWCHYLd+pVHzkzriJ28r1VnsTx+zehWfC5KxC13IUrRPOglr4Wo/SEIsVlm7PxoVaK0VkbfKZOSp8TiV1Dm+UI7Y39XDRzzebUQ="
  file_glob: true
  file:
  - $GOPATH/src/github.com/containerd/containerd/releases/*.tar.gz
  - $GOPATH/src/github.com/containerd/containerd/releases/*.tar.gz.sha256sum
  - $GOPATH/src/github.com/containerd/containerd/releases/runc.*
  name: ${TRAVIS_TAG} Build $(date +'%d.%m.%Y %R')
  skip_cleanup: true
  on:
    repo: kind-ci/containerd-nightlies
    tags: true
